In [10]:
import pandas as pd
dia = pd.read_csv('C:\\Users\\arun245104\\Downloads\\diabetes.csv').dropna()

In [11]:
dia

,PatientID,Pregnancies,PlasmaGlucose,DiastolicBloodPressure,TricepsThickness,SerumInsulin,BMI,DiabetesPedigree,Age,Diabetic
0,1354778,0,171,80,34,23,43.509726,1.213191,21,0
1,1147438,8,92,93,47,36,21.240576,0.158365,23,0
2,1640031,7,115,47,52,35,41.511523,0.079019,23,0
3,1883350,9,103,78,25,304,29.582192,1.282870,43,1
4,1424119,1,85,59,27,35,42.604536,0.549542,22,0
...,...,...,...,...,...,...,...,...,...,...
14995,1490300,10,65,60,46,177,33.512468,0.148327,41,1
14996,1744410,2,73,66,27,168,30.132636,0.862252,38,1
14997,1742742,0,93,89,43,57,18.690683,0.427049,24,0
14998,1099353,0,132,98,18,161,19.791645,0.302257,23,0


In [12]:
dia.shape

(15000, 10)

In [15]:
dia[0]

KeyError: 0

In [16]:
dia.columns

Index(['PatientID', 'Pregnancies', 'PlasmaGlucose', 'DiastolicBloodPressure',
       'TricepsThickness', 'SerumInsulin', 'BMI', 'DiabetesPedigree', 'Age',
       'Diabetic'],
      dtype='object')

In [20]:
dia.iloc[2,:]

PatientID                 1.640031e+06
Pregnancies               7.000000e+00
PlasmaGlucose             1.150000e+02
DiastolicBloodPressure    4.700000e+01
TricepsThickness          5.200000e+01
SerumInsulin              3.500000e+01
BMI                       4.151152e+01
DiabetesPedigree          7.901857e-02
Age                       2.300000e+01
Diabetic                  0.000000e+00
Name: 2, dtype: float64

In [21]:
dia.iloc[1:4,0:2]

,PatientID,Pregnancies
1,1147438,8
2,1640031,7
3,1883350,9


In [22]:
dia.iloc[0:,0:]

,PatientID,Pregnancies,PlasmaGlucose,DiastolicBloodPressure,TricepsThickness,SerumInsulin,BMI,DiabetesPedigree,Age,Diabetic
0,1354778,0,171,80,34,23,43.509726,1.213191,21,0
1,1147438,8,92,93,47,36,21.240576,0.158365,23,0
2,1640031,7,115,47,52,35,41.511523,0.079019,23,0
3,1883350,9,103,78,25,304,29.582192,1.282870,43,1
4,1424119,1,85,59,27,35,42.604536,0.549542,22,0
...,...,...,...,...,...,...,...,...,...,...
14995,1490300,10,65,60,46,177,33.512468,0.148327,41,1
14996,1744410,2,73,66,27,168,30.132636,0.862252,38,1
14997,1742742,0,93,89,43,57,18.690683,0.427049,24,0
14998,1099353,0,132,98,18,161,19.791645,0.302257,23,0


In [24]:
dia.mean()


PatientID                 1.502922e+06
Pregnancies               3.224533e+00
PlasmaGlucose             1.078569e+02
DiastolicBloodPressure    7.122067e+01
TricepsThickness          2.881400e+01
SerumInsulin              1.378521e+02
BMI                       3.150965e+01
DiabetesPedigree          3.989677e-01
Age                       3.013773e+01
Diabetic                  3.333333e-01
dtype: float64

In [33]:
dia

,PatientID,Pregnancies,PlasmaGlucose,DiastolicBloodPressure,TricepsThickness,SerumInsulin,BMI,DiabetesPedigree,Age,Diabetic
0,1354778,0,171,80,34,23,43.509726,1.213191,21,0
1,1147438,8,92,93,47,36,21.240576,0.158365,23,0
2,1640031,7,115,47,52,35,41.511523,0.079019,23,0
3,1883350,9,103,78,25,304,29.582192,1.282870,43,1
4,1424119,1,85,59,27,35,42.604536,0.549542,22,0
...,...,...,...,...,...,...,...,...,...,...
14995,1490300,10,65,60,46,177,33.512468,0.148327,41,1
14996,1744410,2,73,66,27,168,30.132636,0.862252,38,1
14997,1742742,0,93,89,43,57,18.690683,0.427049,24,0
14998,1099353,0,132,98,18,161,19.791645,0.302257,23,0


In [39]:
dia.iloc[0,[0,1,2,3]]

PatientID                 1354778.0
Pregnancies                     0.0
PlasmaGlucose                 171.0
DiastolicBloodPressure         80.0
Name: 0, dtype: float64

In [58]:
a=dia.loc[:,'Pregnancies']
b= dia.loc[:,'BMI']
a,b

(0         0
 1         8
 2         7
 3         9
 4         1
          ..
 14995    10
 14996     2
 14997     0
 14998     0
 14999     3
 Name: Pregnancies, Length: 15000, dtype: int64,
 0        43.509726
 1        21.240576
 2        41.511523
 3        29.582192
 4        42.604536
            ...    
 14995    33.512468
 14996    30.132636
 14997    18.690683
 14998    19.791645
 14999    36.215437
 Name: BMI, Length: 15000, dtype: float64)

In [64]:
dia.loc[dia['Age'] ==21]

,PatientID,Pregnancies,PlasmaGlucose,DiastolicBloodPressure,TricepsThickness,SerumInsulin,BMI,DiabetesPedigree,Age,Diabetic
0,1354778,0,171,80,34,23,43.509726,1.213191,21,0
6,1660149,0,133,47,19,227,21.941357,0.174160,21,0
15,1738587,3,109,77,46,61,19.847312,0.204345,21,1
25,1710438,9,104,68,42,40,51.855401,0.182938,21,1
26,1139740,6,135,91,31,14,45.274113,0.707163,21,1
...,...,...,...,...,...,...,...,...,...,...
14961,1808006,0,153,49,17,23,37.888759,0.145602,21,0
14967,1053260,3,45,98,15,141,26.860006,0.152587,21,1
14973,1398288,1,71,71,16,32,46.382806,0.107268,21,0
14982,1886535,6,86,73,10,412,38.204487,0.199657,21,1


In [66]:
dia[dia['Age'] ==22]

,PatientID,Pregnancies,PlasmaGlucose,DiastolicBloodPressure,TricepsThickness,SerumInsulin,BMI,DiabetesPedigree,Age,Diabetic
4,1424119,1,85,59,27,35,42.604536,0.549542,22,0
10,1943830,1,88,86,11,58,43.225041,0.230285,22,0
28,1975790,0,119,50,52,16,45.391121,0.270567,22,0
41,1375088,1,85,80,35,190,50.504035,0.118579,22,0
43,1835203,0,76,85,25,471,18.856769,0.771367,22,0
...,...,...,...,...,...,...,...,...,...,...
14975,1761875,8,68,67,7,224,38.903552,0.133446,22,0
14978,1591646,8,88,67,39,387,20.858520,0.899682,22,1
14983,1020389,8,113,66,43,214,19.138671,0.143024,22,1
14986,1562505,6,119,76,15,80,36.680032,0.200504,22,1


In [67]:
dia.query('Age == 21')

,PatientID,Pregnancies,PlasmaGlucose,DiastolicBloodPressure,TricepsThickness,SerumInsulin,BMI,DiabetesPedigree,Age,Diabetic
0,1354778,0,171,80,34,23,43.509726,1.213191,21,0
6,1660149,0,133,47,19,227,21.941357,0.174160,21,0
15,1738587,3,109,77,46,61,19.847312,0.204345,21,1
25,1710438,9,104,68,42,40,51.855401,0.182938,21,1
26,1139740,6,135,91,31,14,45.274113,0.707163,21,1
...,...,...,...,...,...,...,...,...,...,...
14961,1808006,0,153,49,17,23,37.888759,0.145602,21,0
14967,1053260,3,45,98,15,141,26.860006,0.152587,21,1
14973,1398288,1,71,71,16,32,46.382806,0.107268,21,0
14982,1886535,6,86,73,10,412,38.204487,0.199657,21,1


In [69]:
dia[dia.Age==25]

,PatientID,Pregnancies,PlasmaGlucose,DiastolicBloodPressure,TricepsThickness,SerumInsulin,BMI,DiabetesPedigree,Age,Diabetic
13,1669231,7,110,82,16,44,36.089293,0.281276,25,0
18,1536832,8,117,39,32,164,21.230996,0.089363,25,0
23,1218879,1,124,82,42,266,34.985772,0.083335,25,0
27,1398321,3,163,87,42,428,18.571188,0.777016,25,0
33,1140806,3,123,61,29,46,28.091062,1.893404,25,0
...,...,...,...,...,...,...,...,...,...,...
14926,1339904,5,87,115,11,49,38.540180,0.206562,25,0
14930,1546639,2,89,79,49,50,39.536521,0.599718,25,0
14946,1952386,1,95,40,32,167,21.198225,0.781019,25,0
14957,1582615,0,156,57,35,38,21.473855,0.127779,25,0


In [70]:
dia.head()

,PatientID,Pregnancies,PlasmaGlucose,DiastolicBloodPressure,TricepsThickness,SerumInsulin,BMI,DiabetesPedigree,Age,Diabetic
0,1354778,0,171,80,34,23,43.509726,1.213191,21,0
1,1147438,8,92,93,47,36,21.240576,0.158365,23,0
2,1640031,7,115,47,52,35,41.511523,0.079019,23,0
3,1883350,9,103,78,25,304,29.582192,1.282870,43,1
4,1424119,1,85,59,27,35,42.604536,0.549542,22,0


In [71]:
dia.isnull()

,PatientID,Pregnancies,PlasmaGlucose,DiastolicBloodPressure,TricepsThickness,SerumInsulin,BMI,DiabetesPedigree,Age,Diabetic
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
14995,False,False,False,False,False,False,False,False,False,False
14996,False,False,False,False,False,False,False,False,False,False
14997,False,False,False,False,False,False,False,False,False,False
14998,False,False,False,False,False,False,False,False,False,False


In [72]:
dia.isnull().sum()

PatientID                 0
Pregnancies               0
PlasmaGlucose             0
DiastolicBloodPressure    0
TricepsThickness          0
SerumInsulin              0
BMI                       0
DiabetesPedigree          0
Age                       0
Diabetic                  0
dtype: int64

In [73]:
dia[dia.isnull().any(axis=1)]

,PatientID,Pregnancies,PlasmaGlucose,DiastolicBloodPressure,TricepsThickness,SerumInsulin,BMI,DiabetesPedigree,Age,Diabetic


In [76]:
data = [50,50,47,97,49,3,53,42,26,74,82,62,37,15,70,27,36,35,48,52,63,64]
print(data)

[50, 50, 47, 97, 49, 3, 53, 42, 26, 74, 82, 62, 37, 15, 70, 27, 36, 35, 48, 52, 63, 64]


In [79]:
import numpy as np
grades = np.array(data)
print(grades)

[50 50 47 97 49  3 53 42 26 74 82 62 37 15 70 27 36 35 48 52 63 64]


In [80]:

print (type(data),'x 2:', data * 2)
print('---')
print (type(grades),'x 2:', grades * 2)

<class 'list'> x 2: [50, 50, 47, 97, 49, 3, 53, 42, 26, 74, 82, 62, 37, 15, 70, 27, 36, 35, 48, 52, 63, 64, 50, 50, 47, 97, 49, 3, 53, 42, 26, 74, 82, 62, 37, 15, 70, 27, 36, 35, 48, 52, 63, 64]
---
<class 'numpy.ndarray'> x 2: [100 100  94 194  98   6 106  84  52 148 164 124  74  30 140  54  72  70
  96 104 126 128]


In [81]:

# Define an array of study hours
study_hours = [10.0,11.5,9.0,16.0,9.25,1.0,11.5,9.0,8.5,14.5,15.5,
               13.75,9.0,8.0,15.5,8.0,9.0,6.0,10.0,12.0,12.5,12.0]

# Create a 2D array (an array of arrays)
student_data = np.array([study_hours, grades])

# display the array
student_data

array([[10.  , 11.5 ,  9.  , 16.  ,  9.25,  1.  , 11.5 ,  9.  ,  8.5 ,
        14.5 , 15.5 , 13.75,  9.  ,  8.  , 15.5 ,  8.  ,  9.  ,  6.  ,
        10.  , 12.  , 12.5 , 12.  ],
       [50.  , 50.  , 47.  , 97.  , 49.  ,  3.  , 53.  , 42.  , 26.  ,
        74.  , 82.  , 62.  , 37.  , 15.  , 70.  , 27.  , 36.  , 35.  ,
        48.  , 52.  , 63.  , 64.  ]])

In [82]:

import pandas as pd

df_students = pd.DataFrame({'Name': ['Dan', 'Joann', 'Pedro', 'Rosie', 'Ethan', 'Vicky', 'Frederic', 'Jimmie', 
                                     'Rhonda', 'Giovanni', 'Francesca', 'Rajab', 'Naiyana', 'Kian', 'Jenny',
                                     'Jakeem','Helena','Ismat','Anila','Skye','Daniel','Aisha'],
                            'StudyHours':student_data[0],
                            'Grade':student_data[1]})

df_students 

,Name,StudyHours,Grade
0,Dan,10.00,50.0
1,Joann,11.50,50.0
2,Pedro,9.00,47.0
3,Rosie,16.00,97.0
4,Ethan,9.25,49.0
5,Vicky,1.00,3.0
6,Frederic,11.50,53.0
7,Jimmie,9.00,42.0
8,Rhonda,8.50,26.0
9,Giovanni,14.50,74.0


In [85]:
df_students.isnull()

,Name,StudyHours,Grade
0,False,False,False
1,False,False,False
2,False,False,False
3,False,False,False
4,False,False,False
5,False,False,False
6,False,False,False
7,False,False,False
8,False,False,False
9,False,False,False


In [87]:
df_students.isnull().sum()

Name          0
StudyHours    0
Grade         0
dtype: int64

In [88]:
import pandas as pd
import numpy as np

# Sample data for df_students
data = {'Name': [False] * 22,
        'StudyHours': [False] * 22,
        'Grade': [False] * 22}

df_students = pd.DataFrame(data)

# Function to randomly insert NaN values
def add_null_values(df, num_nulls):
    for _ in range(num_nulls):
        # Randomly choose a row and column to insert NaN
        row = np.random.randint(0, df.shape[0])  # Random row
        col = np.random.choice(df.columns)      # Random column
        df.loc[row, col] = np.nan  # Set the value to NaN
    return df

# Add 5 null values to the DataFrame
df_students = add_null_values(df_students, 5)

# Show the updated DataFrame
print(df_students)


     Name StudyHours  Grade
0   False      False  False
1   False      False  False
2   False        NaN  False
3   False      False  False
4   False      False  False
5   False      False  False
6   False      False  False
7   False      False  False
8     NaN      False  False
9   False      False  False
10    NaN      False  False
11  False      False  False
12  False      False  False
13  False      False  False
14  False      False  False
15    NaN      False  False
16  False      False  False
17  False      False  False
18  False      False  False
19  False      False  False
20    NaN      False  False
21  False      False  False


C:\Users\arun245104\AppData\Local\Temp\1\ipykernel_23612\460119845.py:17: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'nan' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  df.loc[row, col] = np.nan  # Set the value to NaN
C:\Users\arun245104\AppData\Local\Temp\1\ipykernel_23612\460119845.py:17: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'nan' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  df.loc[row, col] = np.nan  # Set the value to NaN


In [91]:
df_students.isnull().sum()

Name          4
StudyHours    1
Grade         0
dtype: int64

In [96]:
df_students.isnull().any()

Name           True
StudyHours     True
Grade         False
dtype: bool

In [97]:
df_students.isnull().all()

Name          False
StudyHours    False
Grade         False
dtype: bool

In [100]:
df_students[df_students.isnull().any(axis=1)]

,Name,StudyHours,Grade
2,False,NaN,False
8,NaN,False,False
10,NaN,False,False
15,NaN,False,False
20,NaN,False,False


In [103]:
df_students.StudyHours = df_students.StudyHours.fillna(df_students.StudyHours.mean())


In [104]:
df_students

,Name,StudyHours,Grade
0,False,False,False
1,False,False,False
2,False,0.0,False
3,False,False,False
4,False,False,False
5,False,False,False
6,False,False,False
7,False,False,False
8,NaN,False,False
9,False,False,False


In [107]:
df_students= df_students.dropna(axis=0 ,how= 'any')
df_students

,Name,StudyHours,Grade
0,False,False,False
1,False,False,False
2,False,0.0,False
3,False,False,False
4,False,False,False
5,False,False,False
6,False,False,False
7,False,False,False
9,False,False,False
11,False,False,False


In [108]:
dia

,PatientID,Pregnancies,PlasmaGlucose,DiastolicBloodPressure,TricepsThickness,SerumInsulin,BMI,DiabetesPedigree,Age,Diabetic
0,1354778,0,171,80,34,23,43.509726,1.213191,21,0
1,1147438,8,92,93,47,36,21.240576,0.158365,23,0
2,1640031,7,115,47,52,35,41.511523,0.079019,23,0
3,1883350,9,103,78,25,304,29.582192,1.282870,43,1
4,1424119,1,85,59,27,35,42.604536,0.549542,22,0
...,...,...,...,...,...,...,...,...,...,...
14995,1490300,10,65,60,46,177,33.512468,0.148327,41,1
14996,1744410,2,73,66,27,168,30.132636,0.862252,38,1
14997,1742742,0,93,89,43,57,18.690683,0.427049,24,0
14998,1099353,0,132,98,18,161,19.791645,0.302257,23,0


In [118]:
mean_dia= dia['Pregnancies'].mean()
mean_plasma= dia['PlasmaGlucose'].mean()
mean_Trceps=dia['TricepsThickness'].mean()
print('Average of ',mean_dia,mean_plasma,mean_Trceps)


Average of  3.2245333333333335 107.85686666666666 28.814


In [123]:
dia[(dia.Pregnancies>mean_dia)&(dia.PlasmaGlucose > mean_plasma)]

,PatientID,Pregnancies,PlasmaGlucose,DiastolicBloodPressure,TricepsThickness,SerumInsulin,BMI,DiabetesPedigree,Age,Diabetic
2,1640031,7,115,47,52,35,41.511523,0.079019,23,0
12,1848869,5,114,101,43,70,36.495320,0.079190,38,1
13,1669231,7,110,82,16,44,36.089293,0.281276,25,0
18,1536832,8,117,39,32,164,21.230996,0.089363,25,0
26,1139740,6,135,91,31,14,45.274113,0.707163,21,1
...,...,...,...,...,...,...,...,...,...,...
14983,1020389,8,113,66,43,214,19.138671,0.143024,22,1
14984,1733877,8,119,70,21,63,51.877294,0.172106,44,1
14986,1562505,6,119,76,15,80,36.680032,0.200504,22,1
14989,1317369,6,132,90,38,128,20.647840,0.265326,43,0


In [127]:
dia[(dia.PlasmaGlucose<mean_plasma) & (dia.TricepsThickness>mean_Trceps)]

,PatientID,Pregnancies,PlasmaGlucose,DiastolicBloodPressure,TricepsThickness,SerumInsulin,BMI,DiabetesPedigree,Age,Diabetic
1,1147438,8,92,93,47,36,21.240576,0.158365,23,0
7,1458769,0,67,87,43,36,18.277723,0.236165,26,0
8,1201647,8,80,95,33,24,26.624929,0.443947,53,1
9,1403912,1,72,31,40,42,36.889576,0.103944,26,0
11,1824483,3,94,96,31,36,21.294479,0.259020,23,0
...,...,...,...,...,...,...,...,...,...,...
14980,1552787,9,56,48,35,21,19.321562,0.614377,23,0
14987,1840388,2,81,79,69,20,35.093644,0.766683,47,1
14994,1453189,0,72,99,32,32,20.932808,0.545038,22,0
14995,1490300,10,65,60,46,177,33.512468,0.148327,41,1


In [136]:
dia[dia.PlasmaGlucose > mean_plasma].Grade.mean()

AttributeError: 'DataFrame' object has no attribute 'Grade'

In [ ]:
##will continue forming Neural Network

In [149]:
pip install tensorflow


Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.

   ---------------------------------------- 0.0/390.3 MB ? eta -:--:--
   ---------------------------------------- 1.3/390.3 MB 6.7 MB/s eta 0:00:58
   ---------------------------------------- 3.4/390.3 MB 8.8 MB/s eta 0:00:45
    --------------------------------------- 6.6/390.3 MB 11.2 MB/s eta 0:00:35
    --------------------------------------- 9.7/390.3 MB 12.3 MB/s eta 0:00:31
   - -------------------------------------- 13.1/390.3 MB 13.1 MB/s eta 0:00:29
   - -------------------------------------- 16.0/390.3 MB 13.3 MB/s eta 0:00:29
   -- ------------------------------------- 19.7/390.3 MB 14.0 MB/s eta 0:00:27
   -- ------------------------------------- 23.9/390.3 MB 14.8 MB/s eta 0:00:25
   -- ------------------------------------- 27.5/390.3 MB 15.0 MB/s eta 0:00:25
   --- ------------------------------------ 30.7/390.3 MB 15.1 MB/s eta

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  You can safely remove it manually.
  You can safely remove it manually.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


Deep Learning with TensorFlow


In [137]:
dia

,PatientID,Pregnancies,PlasmaGlucose,DiastolicBloodPressure,TricepsThickness,SerumInsulin,BMI,DiabetesPedigree,Age,Diabetic
0,1354778,0,171,80,34,23,43.509726,1.213191,21,0
1,1147438,8,92,93,47,36,21.240576,0.158365,23,0
2,1640031,7,115,47,52,35,41.511523,0.079019,23,0
3,1883350,9,103,78,25,304,29.582192,1.282870,43,1
4,1424119,1,85,59,27,35,42.604536,0.549542,22,0
...,...,...,...,...,...,...,...,...,...,...
14995,1490300,10,65,60,46,177,33.512468,0.148327,41,1
14996,1744410,2,73,66,27,168,30.132636,0.862252,38,1
14997,1742742,0,93,89,43,57,18.690683,0.427049,24,0
14998,1099353,0,132,98,18,161,19.791645,0.302257,23,0


In [138]:
dia.sample(10)

,PatientID,Pregnancies,PlasmaGlucose,DiastolicBloodPressure,TricepsThickness,SerumInsulin,BMI,DiabetesPedigree,Age,Diabetic
14814,1393465,0,81,51,42,34,21.777423,0.444426,23,0
3257,1330931,2,79,55,42,355,20.649710,0.195384,21,0
4521,1625358,4,118,60,15,214,29.378815,0.198456,21,1
12051,1153574,5,149,63,41,558,45.221662,0.607661,37,1
12332,1970419,0,52,49,34,74,39.411184,0.107664,23,0
1117,1204970,8,126,81,20,67,50.327008,1.187352,22,1
1191,1564664,0,134,90,31,166,21.885160,0.302428,22,0
6381,1424655,1,174,78,11,41,29.605179,0.602708,24,0
8706,1854504,3,114,63,48,29,35.850332,0.146532,23,1
9180,1461270,0,85,83,17,142,50.092461,0.174132,24,0


In [139]:
diabetic_classes = ['Diabetic','Non Diabetic']
print(sample.columns[0:5].values,'Diabetic')
for index,row in dia.sample(10).iterrows():
        print('[', row['PatientID'], row['Pregnancies'], row['PlasmaGlucose'], row['DiastolicBloodPressure'], 
          row['TricepsThickness'], int(row['SerumInsulin']), ']', diabetic_classes[int(row['Diabetic'])])

NameError: name 'sample' is not defined

In [140]:
import pandas as pd

# Assuming 'dia' is already defined and loaded with the data.

# Define the diabetic classes
diabetic_classes = ['Non Diabetic', 'Diabetic']

# Print the first five columns of the DataFrame
print(dia.columns[0:5].values, 'Diabetic')

# Sample 10 rows and iterate over them
for index, row in dia.sample(10).iterrows():
    # Print the row values, using column names for clarity
    print('[', row['PatientID'], row['Pregnancies'], row['PlasmaGlucose'], row['DiastolicBloodPressure'], 
          row['TricepsThickness'], int(row['SerumInsulin']), ']', diabetic_classes[int(row['Diabetic'])])


['PatientID' 'Pregnancies' 'PlasmaGlucose' 'DiastolicBloodPressure'
 'TricepsThickness'] Diabetic
[ 1534261.0 0.0 156.0 86.0 11.0 196 ] Non Diabetic
[ 1782337.0 0.0 141.0 83.0 29.0 24 ] Non Diabetic
[ 1189217.0 9.0 141.0 54.0 10.0 68 ] Non Diabetic
[ 1010267.0 0.0 170.0 77.0 42.0 71 ] Non Diabetic
[ 1448054.0 1.0 71.0 61.0 17.0 63 ] Non Diabetic
[ 1435453.0 7.0 152.0 96.0 15.0 261 ] Diabetic
[ 1090618.0 0.0 83.0 57.0 34.0 183 ] Non Diabetic
[ 1552962.0 0.0 71.0 99.0 33.0 132 ] Non Diabetic
[ 1121321.0 1.0 161.0 69.0 31.0 58 ] Non Diabetic
[ 1203246.0 1.0 85.0 96.0 31.0 185 ] Non Diabetic


In [202]:
from sklearn.model_selection import train_test_split
features=  ['Pregnancies', 'PlasmaGlucose', 'DiastolicBloodPressure', 'TricepsThickness']
label = 'Diabetic'
#split data 70%-30% into traning
x_train ,x_test,y_train,y_test1 = train_test_split(dia[features].values,
                                                  dia[label].values,
                                                  test_size=0.30,
                                                  random_state=0)
print('Traning set:%d, Test set : %d \n'%(len(x_train),len(x_test)))
print('sample of features and labels;')

for n in range(0,24):
    print(x_train[n],y_train[n],'('+diabetic_classes[y_train[n]]+')')

Traning set:10500, Test set : 4500 

sample of features and labels;
[  8 118  91  11] 0 (Non Diabetic)
[ 3 67 78  9] 0 (Non Diabetic)
[ 0 91 58 10] 0 (Non Diabetic)
[ 0 76 49 10] 0 (Non Diabetic)
[ 1 92 57 34] 0 (Non Diabetic)
[ 0 91 54 44] 0 (Non Diabetic)
[  6 106  89  40] 1 (Diabetic)
[  8 107  56  34] 0 (Non Diabetic)
[ 1 91 56 34] 0 (Non Diabetic)
[ 0 97 70 11] 0 (Non Diabetic)
[ 4 96 97 16] 1 (Diabetic)
[  5 172  91  10] 0 (Non Diabetic)
[  1 115  73   7] 0 (Non Diabetic)
[ 0 71 53 35] 0 (Non Diabetic)
[ 0 97 81 33] 0 (Non Diabetic)
[ 1 47 51 38] 0 (Non Diabetic)
[ 1 79 45 18] 0 (Non Diabetic)
[  3 170  94  35] 0 (Non Diabetic)
[ 10 172  78  11] 1 (Diabetic)
[  7 109  69  13] 1 (Diabetic)
[  3 119  98  42] 1 (Diabetic)
[  1 126  82  42] 0 (Non Diabetic)
[  2 172  46  11] 1 (Diabetic)
[  3  67 115  11] 0 (Non Diabetic)


In [164]:
import tensorflow 
from tensorflow import keras
from tensorflow.keras import models
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras import utils
from tensorflow.keras import optimizers

#set random seed for reproducabiltiy 
tensorflow.random.set_seed(0)

print('Libraries imported.')
print('Tensorflow version :',tensorflow.__version__)

Libraries imported.
Tensorflow version : 2.18.0


In [199]:
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')

#set data types for categorical labels 
y_train= utils.to_categorical(y_train)
y_test1=utils.to_categorical(y_test1)
print('Ready..2.')

Ready..2.



Define a neural network

In [200]:
hl =10 #Number of Hidden layer nodes
model= Sequential()
model.add(Dense(hl,input_dim=len(features),activation='relu'))
model.add(Dense(hl,input_dim=hl,activation='relu'))
model.add(Dense(len(diabetic_classes),input_dim=hl,activation ='softmax'))

print(model.summary())

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_13 (Dense)                     │ (None, 10)                  │              50 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_14 (Dense)                     │ (None, 10)                  │             110 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_15 (Dense)                     │ (None, 2)                   │              22 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 182 (728.00 B)

 Trainable params: 182 (728.00 B)

 Non-trainable params: 0 (0.00 B)

None


Train the model


In [201]:
#hyper-parameters for optimizer 
learning_rate = 0.00001
#opt = optimizer.Adam (lr=Learnign rate)
opt= optimizers.Adam(learning_rate=0.00001)

model.compile(loss='categorical_crossentropy',
              optimizer=opt,
              metrics=['accuracy'])
num_epochs= 50 
history = model.fit(x_train,y_train,epochs=num_epochs,batch_size=10,validation_data=(x_test,y_test1))

ValueError: Data cardinality is ambiguous. Make sure all arrays contain the same number of samples.'x' sizes: 10500
'y' sizes: 4500
